language: scala
sudo: required

jdk:
  - openjdk8

scala:
  - 2.11.12
  - 2.12.10

services:
  - docker

script: ./scripts/test.sh

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.m2"

ignore:
  - "changelog/*"
  - "scripts/*"

before_install:
  - |
    if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_56e8fc46d7cd_key -iv $encrypted_56e8fc46d7cd_iv -in secrets.tar.enc -out secrets.tar -d
      tar xvf secrets.tar
      chmod 777 scripts/test.sh
    fi

jobs:
  include:
    - stage: publish
      script: chmod 777 scripts/publish.sh && ./scripts/publish.sh
      scala: 2.12.10
    - stage: release
      script: chmod 777 scripts/release.sh && ./scripts/release.sh
      scala: 2.12.10

stages:
  - name: test
  - name: publish
    if: branch = master AND type != pull_request
  - name: release
    if: branch = master AND type != pull_request
