language: scala
sudo: required
scala:
- 2.11.8
- 2.12.7
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
before_install:
- |
  if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_56e8fc46d7cd_key -iv $encrypted_56e8fc46d7cd_iv -in secrets.tar.enc -out secrets.tar -d
    tar xvf secrets.tar
  fi
script:
- sbt ++$TRAVIS_SCALA_VERSION rddTest dsTest streamingTest structuredTest
after_success:
- |
  if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    sbt ++${TRAVIS_SCALA_VERSION} rddPublish dsPublish streamingPublish structuredPublish
  fi
env:
  global:
  - secure: o7yWIqfBDp55nVhOE9HR+V1bYtRJngr1Qc0aR3W9nLIhnMcQLCLRRiOQByTklgky+h+oq8PaNJOPL6IgIgw1/J0xsp6HVIet0VLDolWeKUgFLNbi+ZqfBwI1FMu1XmJTLxEF6OAjAErLV3FSi8DEx2cl+3FpKIFRR1Lcl26/mWkmcco67WOgZkerRi6RRhJlsloTD9wB9SHQjNV09z67vbAos/vUslQovuu/z7VsOk5wkJLzHEnXyMUAdhh3DqL/MVtlvgwIrt/nIllg7iORsluzlOmCo+TFh9UmkTN9gbwDR9fx/griryl78feflz5yFRRmgXiwaYEcGF5PwEc80MJpMldYPuCWO+qfPcF+0ULnoxaw53NWNBt6ASriUnqBzcQRcA5H2Ekxe6v6RCJXjIkO/Xrq6QF+DCFCfYnUYfaHdKD+rwX1XwiTeHN3cWOSi5b6XiuajLQBTU/8SHWRG5AfGdHKg20f/Cq8+1xxtldJ/GSOim2yOgiEKP6gQOvky7e0euv5XTqOwgWTotyuFe5q5xixP8l0rK0TrShWz+CMQBdJSnyesKAhiZFI+B8C5B7adrYLxMOiD2CKDzLibXxlikUvnCXLymF666McY+dBmbWza1lT55GV/4FqNYWd+vxDeVtP9ghPJGl9ffmuo3GoK9igt3EKDMUW5jn5Otc=
  - secure: dcdLS5/dDJRkmvc4oZFxSnckjlHkQs1g1bvdNVgabazWimNvxRs4h/JJQH/+w2XaNtjfDy24E0g8SOegGcXH1lLF7CTf4EksUH7ODeDlaK5yX2RMWBOgAvVgwSo1RmJpiIvadVx2TqMct4Km1ZMhB+dBfWo82keVLduUE4M+kyhE7DBkF4Be4HCT/FX2qtuvIzWT0fwxVw2QjxRo4jWhUoTCMyG5b4vgn+cknIDdg3p3KXrymmPqgccFwOtFHjqzUtMKqjsEmBwMQ1Sp19HyLi0+wekPL5u1ngxqhhbutnyz9kHV2iZDFmgIhkHNADG/1anAgdF6gu4QghixPxllMJLw5rzMeA2bH7w1WiNmy8UU32wNg3vKWuiqC0TqwqGz2j2G092caji6vZn7vYr/06R3HN2TLv+ZaqQ1BENa4BS0aEHSguCtjRQpdGCyYkjXYYK8C+6LxXSBMXlJjH67laYopdN65/dT/ZmyWO10sgK2dgxTxkAcdArt7lTkt87BFzz+9Nb58cDuH12/Z6Nm6stIDxO/afPVRL6pW8tD6qZidkNM1vf8mjSpAAY5hbRyBC/7SoWIR7LB3ADTAOSkIJ0tJiSfbXOangWyW++gMOMnXcpKSRkb8LBnvqsz1FBM3n0LXp6IhEz4m5efLqya7eXq2Ta77di4kDG1XZTbUXM=
  - secure: Sh/RPYvj3bYbIAYokxOgceZ7TYZmWgtWkhYKehw9vy4G7VH0HXdGiITl7I/lkgqKmR6uFG6hZASMcTyv3wQbKa3wkN9B9shyWuDAfWHgx+PYO+GmZvXem8M54Ll90X2AQxKMKJDiHdZGtGAcKcdlTCLC5KuvQ9hL2YGq3CkX3kicl0804WJPeOjUstxOXTbzUAt3EQxIViJtGqa0JtnovneRIAuOU9tdNTJW3lG5mPdOIFKB+6MdvaXJWXh/hOptHZxiOeVv3NjU9uG5IL17qdQ9IwmVrVJpZyRqlCcSqOB+GN/asKCjSLOQ9D+0wpLLWMwEYhurMUTVvI0LLN7N1JvBT114FtWpAAIilxwO2UCyasDsSc4tQMkzb/XyKXzFVwUTPp6NOYaCg0Z9+MDPZ+V5+QRtTLMaTvkD7JSODdFckcI+bXcSPwD/LIKBbAhhhmxQ+yr/nFGzo5kBPgShI5JFlboZQc3Cs/hiAU30tW7gpTVx+00BGYaQB3JIKs+0JZkKda/GCpo3Re0TSDv7BMHzmOV/W/lvtLJWmnPe/k+EOGjDEa6WSkjbbtvKBdEIfhzm/q1SjlG+mkzn1YD+1Ytze6X+q6Jbc0llH0diyY9A6o1Epxlf14HNDiTMMyOQX4RrMHiWQYkh1BWOaZwUy7KOCYUei3A4BwaebfvXPPE=
