language: scala
sudo: required

jdk:
  - oraclejdk8

scala:
  - 2.11.8
  - 2.12.8

services:
  - docker

script: ./scripts/test.sh

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.m2"

ignore:
  - "changelog/*"
  - "scripts/*"

before_install:
  - |
    if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_56e8fc46d7cd_key -iv $encrypted_56e8fc46d7cd_iv -in secrets.tar.enc -out secrets.tar -d
      tar xvf secrets.tar
      chmod 777 scripts/publish.sh scripts/test.sh
    fi

jobs:
  include:
    - stage: deploy_2.11
      script: ./scripts/publish.sh
      name: "Deploying scala 2.11.8 artifacts"
      scala: 2.11.8
    - stage: deploy_2.12
      script: ./scripts/publish.sh
      name: "Deploying scala 2.12.8 artifacts"
      scala: 2.12.8
    - stage: release
      script: chmod 777 scripts/release.sh && ./scripts/release.sh
      scala: 2.12.8

stages:
  - name: test
  - name: deploy_2.11
    if: branch = master AND type != pull_request
  - name: deploy_2.12
    if: branch = master AND type != pull_request
  - name: release
    if: branch = master AND type != pull_request
