language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

sudo: required

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"

services:
  - docker

script:
  - sbt rddTest dsTest streamingTest structuredTest