language: scala
sudo: required

jdk:
  - oraclejdk8

scala:
  - 2.11.8
  - 2.12.8

services:
  - docker

script: ./scripts/test.sh

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.m2"

ignore:
  - "changelog/*"
  - "scripts/*"

before_install:
  - |
    if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_56e8fc46d7cd_key -iv $encrypted_56e8fc46d7cd_iv -in secrets.tar.enc -out secrets.tar -d
      tar xvf secrets.tar
      chmod 777 scripts/publish.sh scripts/test.sh
    fi

jobs:
  include:
    - stage: release
      script: chmod 777 scripts/release.sh && ./scripts/release.sh
      scala: 2.12.8
    - stage: deploy_2.11
      script: ./scripts/publish.sh
      name: "Deploying scala 2.11.8 artifacts"
      scala: 2.11.8
    - stage: deploy_2.12
      script: ./scripts/publish.sh
      name: "Deploying scala 2.12.8 artifacts"
      scala: 2.12.8

stages:
  - name: test
  - name: release
    if: branch = master AND type != pull_request
  - name: deploy_2.11
    if: branch = master AND type != pull_request
  - name: deploy_2.12
    if: branch = master AND type != pull_request

env:
  global:
  - secure: GAJ+zS9f9zOE6YT6Bukx/t0DxrtX7HDBqCjPOIB2/qAh5CyohEz+619iSD03/5pa81cI4H+nWAj7hRiAfhNYseQZmce/qBa3izzWVbBAdsC8FjF17VL4i6dUmfNLr12hrRYbenKOEw6G4M8RsQnso+P8uZxnPyUFyojn43ohUa78OuPhDsefbkVOTgNSGBLVRm6QISbQdRhj7ik0ucCRlBJKwmu0D3T10t6a8YApFvCaK5A4fAZ3p+BtR0xN78VcKp+OY0TZSdkDqBe43JbBGevYoFkO/3Hp4QwGQ0I3tvOWDAL52HZ5Lk6497CTBz2rgofm9jnpF6BD6Bd03yMN6R48f9Z+9AB/AKq9Wkovp8jEuKkii0c+iVXuPKRPzidNVMbZgjaXJi2c8mF5nnj5YOQdYy6rxXKdHQxBLxMeBVqtEYNGHSvh5R8Ny80nDV2qiX6JIvLRTCNU1oaU/mzwWHcdokWFc4JR+BkTgxefFxpy1HyaU05gqdlJFej/uDhL8bZ3GNU4ZM01ptyFKHhsSkJ0cfryuoDhvibFOQH+8NP+ATrKcRRRikdQs0WN9I2LUz/whmq9ew01VK0I2N1zLIn+ckkkqc8QZok+bFKOFXA+1FhGofkqqrc5MQV5M20ZGquS7VQAl883NKL+wbtMjUM8BNls546wRA0ktxPJ2xs=
  - secure: HA9hoo8JgcgSkUhk1WL3ZV+OXrSOLPkxOLS4Zg7BPWLhH+GY4ZzYneamswnvZ/cWV2KuedsG3AFBJOGdL67FiGVBLXdnyv/Bx0F6/L9MOJASc7jZmcKnKc+f7O/k4YeWdCQekekPie1U9NHfaI+zamOJk+BO23pJ5EbYbcylPRgE0QcmA1aNWyS29t7mUOrDPfRDGqy5hDFaNtM/IcPQoASyU5y0VZIaZ5B9oY5/VsuJTdVX8DBOBktSpFk59iVoIuweaiJvcpRg6+q2Gxcd7coT+hzuv1zvjqMVt5gfl/oG3RkieSyYHwqBdJqfjGCBTlydiVip94KvCI06pgT55sqgnh4xcNDuT8hMZesFqG7+m0CvXtpigPcUn8j8Pw75z/5bbB+SdmQZCPyLUjSfHX7kp2GvspK9f+0yjw7rrHGw+CfogEkIm3vFNA5zTAXJj0PCEJ0sdC24kNegZYUqt0wPDsC1tGfBQkKwH1qXlmUYQCB2H0Irz5n2xWkNhwVbwZIyjohZacd3iciUq1+YWdX1b05XZMOBFaYjrH0gUn0Bao6v+ZW6pDUjA3kB/CgK2iXtM1ySPO5M73XH14TGPmRlXWT8IDYRBl/HU2w88440HuArqVCC+y/IU0KgQsHi0bZSW15GikDL+8Sx+JFPsd7HlTT2MpliiCvY/kXn2uk=
  - secure: mVT8r9RVbmEH89uoI7sjVCW0JRsL75KKohbeoDrcf28bGbc7ISbiTnw4wkdVOMwB2hyLVBMVHjAGVpBikJWkpeZph4MnUhyp1xn6koIVTKLglk2Vxh3SGUuzGP6BVRNs5tGfUftEso5gbDAGyHKwaBQHynlezQHXGYo2qEQ2PCRXIu1GN3PGTDJPGsVKXhZCSGOSvs6TPjkVGr4D7BAexbeQE5DNFLX1U+Wvp21l/8TPsv+s2mqiLM+QkWiQshr/z0YdjgCCy4flSgtdhoqcn8JAOp72cA18r//OTKXDV/vKyQUxJjyAeFxd0+30zur8KD5nIZtsVKbC3GbNMlXojZiYBgik8vBSvZrPM79zXmKz3MewtxMPSC912G98OFVyu5Mkwd7voQ+df8HVVomgSchPCvlN5u+N4ZPtmPSUamocJdcV+5Obc/5WqjYIREmMXohNnQPoDrrpdPuJawFyraRiIwJgxDNVj1Dz8jHVAwdWeNaWXc9X5b55jZ6pySz28hZS1nTjxgfuuLbtMFYS/EI/AU1SxeE8TxEKwwrOcJ4XsbC/klDilx/MGTXqpNa/qK9PRtDLPg5y28waVsfJYvGBbIVuYBn6ROcQ8Kc3xDzgxdErlyFBELoPFEu7iW36UpFGVylhrB7H6/upyiaT/d7R0y2rQgiX6quRkLo0T0c=
  - secure: nCbHp2WLRIbOEKgpoIYa2Wz9qbjKPOQSZbVthvlAwiK35ALmZ6gPrDD/B8TMIZOgg0IgcVnrix281+mlP5gwCz5l782DKwDYgE3bGvYhQq1m82zM2KPqfMXQRDDffbNRTOhRZyAs+59yHAzv4RH9VUc4+LFFbZn9qLZXllkydyOe4LOXRqPZG8aBgt48A/aezAUfzpNoLOhi/w96rF/9UNNVkE1RfV3yjvCjIn+B9mDYC9vAKhrnGNno9w1930qcY+14DBPmqWPaEc06optnkABBmWlDpua4yQNeE/wml/8arUFP1Rj+mit/qSt+HEpZtA91IVYJJZuTe7Qs6fzCaLB5yoVOWxc6gvOOrZGpUe2PHUk1ujbXsy+cHQ/IiDW5ED+B7rc5CdTa5eupZAwllkXct495yVCrpihBp/2KuR2Cf5N0a5b1f1F7VBFG3Zg5TEYXDQrpkAo5TtCK/VAPvKzofxRzV6eU/UZI0uUnOCBeqkK4Dy+QjW2Xo6ABrZ+HRe+NEb9mVXbX60I6wFSTsbP2vxclJTRwNa8vAcbDoYL3CXOzMsldA35cY+EU8+OFtf/S/aoCisCxNgHu2Qg3fUnAfR96iucbRieBnaR8pV2YpffOhXCQ1BsR+PKKub3hggi8oV//j3OE6pnLhfFKPfKIWTcAaMSuk2scOQHP+5A=
  - secure: EZ0UIe01/fG3XgXoeo2YErZXAN94KRTSSZSvggeAR/DEEdU0jckJ+UsnGctisobjn0TGvc7eUpbg27Q7beyYA1oY9982G+latoyy8Ckt1rYWElGpgima7ev/Ag8JoZgRdv7Ll3LSUbnCtGTWal6OSqFmisNZPw70BnVpUdQrVDaggHisf8PSVw1HejlOYVNCti89zXSZff38tdKyLjsWbJ/xm5czgH6cnU6Rnns2b9fNTrpJTsMdQaFaVgyHrHvQ0oAAEoe4LMZbCExiC2OsX8qXqvdHVINK5cn2OHRjx/eLaCJroNPt3+99k3VgHNSjfF8nPidKm+tJ6e0nXwnVICnu7jslNGPuUfQga2v6nKDHKAb4RJchrDDJeRA1GGzVK9Dh2RumIve0fsJaSsBJOWK7/2jvLquEMsXkXA4LerAfcXAxXYM57Ih4n0aYkepUJ+ejGqetPOchlcvDihDdQb4J3WGyUcDMJbW7xLDK+f3NLPHpwy5rcjg1hY2HlWuvJKR7H+yksu7LYRDgWrWaWBf33szqZPk5Kf/JFHKYilv6OaJtCVNFIecgrtKkKjmKP6GWcr79RvAEnnnLwtjqFDcEhVBalVCC6KAGY37vtQd1d01u9rnUQZ3Q8fMp7XRvNF2AMSvcUSVEzgQ/QDeinRCWOJ5Jnw7XO7rOHw+aHDs=
